spring.application.name=desirestro-backend
# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:desirestrodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Config
jwt.secret=+O+lT01PYSxnXOMeI0qfYNyOR/eS4VWSlTNTLADH6DIWxBR5QCuuw0aMaNAMfaw8/Q7k5bBFjR9IFAca4Bth4Q==
jwt.expiration=86400000
# 24 hours in ms

# Logging (optional, helpful during dev)
logging.level.com.dts.restro=DEBUG
logging.level.org.springframework.security=DEBUG